const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('assert');
const path = require('path');
const output = process.env.PROACTIVE_QA_OUTPUT || '/tmp/proactive-log-qa';
fs.mkdirSync(output, {recursive:true});
(async () => {
 const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless:true, args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}, acceptDownloads:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const base=process.env.PROACTIVE_QA_URL || 'http://127.0.0.1:8765/qa';
 await page.goto(base); await page.locator('.log-row').first().waitFor();
 assert.equal(await page.title(),'Proactive Log Center QA');
 assert.equal(await page.locator('.log-row').count(),50);
 await page.screenshot({path:path.join(output, 'log-center-desktop.png'),fullPage:false});
 await page.getByRole('button',{name:'下一页',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.logs-pagination').textContent.includes('第 2 页'));
 assert.equal(await page.locator('.log-row').count(),50);
 await page.getByRole('button',{name:'上一页',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.log-row .log-summary')?.textContent.includes('本轮任务终态'));
 await page.locator('.log-row').first().click();
 await page.getByRole('dialog').waitFor();
 assert((await page.getByRole('dialog').innerText()).includes('partial_success'));
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('.log-row').first().click();
 await page.getByRole('button',{name:'查看本轮全部保留事件',exact:true}).click();
 await page.getByRole('button',{name:'返回筛选列表',exact:true}).waitFor();
 assert.equal(await page.locator('.log-row').count(),161);
 assert((await page.locator('body').innerText()).includes('部分成功'));
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'导出筛选 JSON（最多 1000 条）',exact:true}).click();
 const download=await downloadPromise;
 const report=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(report.items.length,161);
 assert.equal(report.applied_filters.trace_id,'ui-run');
 assert(!JSON.stringify(report).includes('SYNTHETIC_UI_SESSION'));
 assert(report.snapshot_max_id);
 await page.getByRole('button',{name:'返回筛选列表',exact:true}).click();
 await page.getByLabel('事件名（精确匹配）',{exact:true}).fill('run.completed');
 await page.getByRole('button',{name:'应用筛选',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.log-row').length===2);
 await page.getByLabel('事件名（精确匹配）',{exact:true}).fill('model.call.started');
 await page.getByRole('button',{name:'应用筛选',exact:true}).click();
 await page.getByText('还没有匹配的日志',{exact:true}).waitFor();
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 await page.locator('.log-row').first().waitFor();
 await page.route('**/api/logs?*',route=>route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'expired'})}));
 await page.getByRole('button',{name:'刷新最新',exact:true}).click();
 await page.getByText('登录已过期，请刷新页面重新登录',{exact:true}).waitFor();
 assert.equal(await page.locator('.log-row').count(),0);
 await page.unroute('**/api/logs?*');
 await page.getByRole('button',{name:'刷新最新',exact:true}).click();
 await page.locator('.log-row').first().waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(output, 'log-center-mobile.png'),fullPage:false});
 await page.locator('.logs-toolbar').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(output,'log-center-mobile-results.png'),fullPage:false});
 const dimensions=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth}));
 assert(dimensions.scrollWidth<=dimensions.innerWidth+1,JSON.stringify(dimensions));
 assert.equal(errors.filter(e=>!e.includes('401')).length,0,JSON.stringify(errors));
 fs.writeFileSync(path.join(output, 'ui-qa-result.json'),JSON.stringify({url:base,viewports:['1440x1000','390x844'],checks:['page identity','nonblank','no framework overlay','console','screenshots','pagination','detail reopen','161-event trace','snapshot export','exact filters','empty','401 recovery','mobile overflow'],errors,dimensions},null,2));
 await browser.close();
 console.log('PASS: 13 browser checks; desktop/mobile screenshots saved.');
})().catch(e=>{console.error(e);process.exit(1)});
